{{- if .Values.controller.enabled }}
# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tekton.name" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "tekton.name" . }}
    app.kubernetes.io/component: controller
    pipeline.tekton.dev/release: v0.11.3
    version: v0.11.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "tekton.name" . }}-controller
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: {{ template "tekton.name" . }}-controller
        app.kubernetes.io/name: {{ template "tekton.name" . }}
        app.kubernetes.io/component: controller
        pipeline.tekton.dev/release: v0.11.3
        version: v0.11.3
    spec:
      serviceAccountName: {{ template "tekton.name" . }}
      containers:
      - name: {{ template "tekton.name" . }}
        image: {{ .Values.image.controller }}:{{ .Values.image.upstreamtag }}
        args: [
          "-kubeconfig-writer-image", "{{ .Values.image.kubeconfigwriter }}:{{ .Values.image.upstreamtag }}",
          "-creds-image", "{{ .Values.image.credsinit }}:{{ .Values.image.upstreamtag }}",
          "-git-image", "{{ .Values.image.gitinit }}:{{ .Values.image.upstreamtag }}",
          "-nop-image", "tianon/true",
          "-shell-image", "busybox",
          "-gsutil-image", "google/cloud-sdk",
          "-entrypoint-image", "{{ .Values.image.entrypoint }}:{{ .Values.image.upstreamtag }}",
          "-pr-image", "{{ .Values.image.pullrequest }}:{{ .Values.image.upstreamtag }}",
          "-imagedigest-exporter-image", "{{ .Values.image.imagedigestexporter }}.{{ .Values.image.upstreamtag }}",
          "-build-gcs-fetcher-image", "{{ .Values.image.gcsfetcher }}.{{ .Values.image.upstreamtag }}",
          "-namespace", "{{ .Release.Namespace }}",
        ]
        env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: CONFIG_OBSERVABILITY_NAME
            value: config-observability
          - name: CONFIG_ARTIFACT_BUCKET_NAME
            value: config-artifact-bucket
          - name: CONFIG_ARTIFACT_PVC_NAME
            value: config-artifact-pvc
          - name: METRICS_DOMAIN
            value: tekton.dev/pipeline
          - name: KUBERNETES_MIN_VERSION
            value: v1.14.0
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "tekton.name" . }}-controller
    pipeline.tekton.dev/release: v0.11.3
    version: v0.11.3
  name: {{ template "tekton.name" . }}-controller
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: {{ template "tekton.name" . }}-controller


{{- end -}}
